### ISSUE TITLE
Threshold values for peaks and valleys.

### ISSUE THREAD

**Issue by manosbar** [BMClab/BMC#2]
I am trying to detect local maxima (\* peaks12\* used in the code below) and local minima (\* peaks13*) from a vector called nrz. All peaks and valleys should be at above 0.25 and below -0.25 respectively. Since my data is per second, I am using mpd=1. I also want to have a new peak or valley only if the vector value has dropped below 0.1 or rised above -0.1. When I use the code below, it doesn’t seem to work for my case.

peak12 = detect_peaks(nrz, mph=0.25 , mpd=1, threshold=0.25, valley=False)
peak13 = detect_peaks(nrz,mph=-0.25, mpd=1, threshold=-0.25, valley=True)

Should I use another parameter when calling the function?
(I also attached a simple .xlsx file with the peaks and valleys I want to detect.
[example.xlsx](https://github.com/demotu/BMC/files/67417/example.xlsx)

**Comment by demotu** [comment]
The problem is that you are calling the function with the wrong parameters. For your case the threshold parameter should be zero. The threshold is how much the peak (or valley) should be greater (or smaller) than its two immediate neighbors. If I call the function with:

``` python
detect_peaks(nrz, mph=0.25, mpd=1, threshold=0, valley=False, show=True)
detect_peaks(nrz, mph=0.25, mpd=1, threshold=0, valley=True, show=True)
```

I get exactly the peaks and valleys you show in the .xlsx file.

I didn't understand "I also want to have a new peak or valley only if the vector value has dropped below 0.1 or rised above -0.1." It should drop or raise relatively to what? Its neighbors? If so, set the threshold parameter. If 0.1 or -0.1 is an absolute quantity, then this is what mph (minimum peak height) sets.

Marcos

**Comment by manosbar** [comment]
Thank you very much Prof. Duarte. The code now works just fine.

About the part: "I also want to have a new peak or valley only if the vector value has dropped below 0.1 or rised above -0.1". I didn't phrase that well. Let me give you an example.

Row - nrz
199 - 0.08
200 - 0.30
201 - 0.19
202 - 0.29
203 - 0.08
204 - 0.29
205 - 0.07

It would be really helpful for my case if the function could give as peaks only rows 200 and 204. Row 202 would not be given as a peak since the nrz value does not have a value below 0.1 since the last peak. However, when it goes under 0.1 in 203 and it can start giving out peaks again, which is row 204.

I will work it out for my case. Thank you once again for your time and prompt reply!

**Comment by demotu** [comment]
I see. You want to (re)start the peak detection when there is a value below 0.1 in your signal and you just want the first peak. This current version of `detect_peaks.py` does not implement that; your case is a very special one.

I think you could solve your problem with:
1.  Detect valleys bellow 0.1
2.  Detect peaks above 0.25
3. Compare the indexes given by steps 1 and 2 to find the first index from step 2 after (greater than) an index from step 1.
4. Repeat step 3 for all indexes from step 1.

**Comment by manosbar** [comment]
Thank you once again for your support.
